
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:4 (project)"
    message: |
      The system is: Linux - 6.6.10-arch1-1 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /bin/clang++ 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.out"
      
      The CXX compiler identification is Clang, found in:
        /home/ghost/progects/sdlqlearn/clearn/CMakeFiles/3.28.1/CompilerIdCXX/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv"
      binary: "/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/usr/bin/clang-scan-deps"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_55389/fast
        make[1]: Entering directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv'
        /usr/bin/make  -f CMakeFiles/cmTC_55389.dir/build.make CMakeFiles/cmTC_55389.dir/build
        make[2]: Entering directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv'
        Building CXX object CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o
        /bin/clang++   -v -MD -MT CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp
        clang version 16.0.6
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /bin
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1
        Found candidate GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
        Selected GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Selected multilib: .;@m64
         (in-process)
         "/usr/bin/clang-16" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv -resource-dir /usr/lib/clang/16 -dependency-file CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1 -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward -internal-isystem /usr/lib/clang/16/include -internal-isystem /usr/local/include -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp
        clang -cc1 version 16.0.6 based upon LLVM 16.0.6 default target x86_64-pc-linux-gnu
        ignoring nonexistent directory "/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1
         /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu
         /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward
         /usr/lib/clang/16/include
         /usr/local/include
         /usr/include
        End of search list.
        Linking CXX executable cmTC_55389
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_55389.dir/link.txt --verbose=1
        /bin/clang++  -v CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_55389 
        clang version 16.0.6
        Target: x86_64-pc-linux-gnu
        Thread model: posix
        InstalledDir: /bin
        Found candidate GCC installation: /bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1
        Found candidate GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
        Selected GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Selected multilib: .;@m64
         "/bin/ld" -pie --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_55389 /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/Scrt1.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crti.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o -L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1 -L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crtn.o
        make[2]: Leaving directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv'
        make[1]: Leaving directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed CXX implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1]
          add: [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu]
          add: [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward]
          add: [/usr/lib/clang/16/include]
          add: [/usr/local/include]
          add: [/usr/include]
        end of search list found
        collapse include dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1] ==> [/include/c++/13.2.1]
        collapse include dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu] ==> [/include/c++/13.2.1/x86_64-pc-linux-gnu]
        collapse include dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward] ==> [/include/c++/13.2.1/backward]
        collapse include dir [/usr/lib/clang/16/include] ==> [/usr/lib/clang/16/include]
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/include/c++/13.2.1;/include/c++/13.2.1/x86_64-pc-linux-gnu;/include/c++/13.2.1/backward;/usr/lib/clang/16/include;/usr/local/include;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/usr/share/cmake/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:4 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_55389/fast]
        ignore line: [make[1]: Entering directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv']
        ignore line: [/usr/bin/make  -f CMakeFiles/cmTC_55389.dir/build.make CMakeFiles/cmTC_55389.dir/build]
        ignore line: [make[2]: Entering directory '/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv']
        ignore line: [Building CXX object CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o]
        ignore line: [/bin/clang++   -v -MD -MT CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -MF CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o.d -o CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -c /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [clang version 16.0.6]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /bin]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Found candidate GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Selected GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [ (in-process)]
        ignore line: [ "/usr/bin/clang-16" -cc1 -triple x86_64-pc-linux-gnu -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCXXCompilerABI.cpp -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv -resource-dir /usr/lib/clang/16 -dependency-file CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o.d -MT CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -sys-header-deps -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1 -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward -internal-isystem /usr/lib/clang/16/include -internal-isystem /usr/local/include -internal-isystem /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdeprecated-macro -fdebug-compilation-dir=/home/ghost/progects/sdlqlearn/clearn/CMakeFiles/CMakeScratch/TryCompile-RPlUzv -ferror-limit 19 -stack-protector 2 -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -x c++ /usr/share/cmake/Modules/CMakeCXXCompilerABI.cpp]
        ignore line: [clang -cc1 version 16.0.6 based upon LLVM 16.0.6 default target x86_64-pc-linux-gnu]
        ignore line: [ignoring nonexistent directory "/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../x86_64-pc-linux-gnu/include"]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1]
        ignore line: [ /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/x86_64-pc-linux-gnu]
        ignore line: [ /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../include/c++/13.2.1/backward]
        ignore line: [ /usr/lib/clang/16/include]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [Linking CXX executable cmTC_55389]
        ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_55389.dir/link.txt --verbose=1]
        ignore line: [/bin/clang++  -v CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -o cmTC_55389 ]
        ignore line: [clang version 16.0.6]
        ignore line: [Target: x86_64-pc-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /bin]
        ignore line: [Found candidate GCC installation: /bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Found candidate GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Selected GCC installation: /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/bin/ld" -pie --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_55389 /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/Scrt1.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crti.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o -L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1 -L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/bin/../lib -L/lib -L/usr/lib CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o -lstdc++ -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o /bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crtn.o]
          arg [/bin/ld] ==> ignore
          arg [-pie] ==> ignore
          arg [--hash-style=gnu] ==> ignore
          arg [--build-id] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-dynamic-linker] ==> ignore
          arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_55389] ==> ignore
          arg [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/Scrt1.o] ==> obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/Scrt1.o]
          arg [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crti.o] ==> obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crti.o]
          arg [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o] ==> obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o]
          arg [-L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1] ==> dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
          arg [-L/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64] ==> dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/usr/bin/../lib] ==> dir [/usr/bin/../lib]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [CMakeFiles/cmTC_55389.dir/CMakeCXXCompilerABI.cpp.o] ==> ignore
          arg [-lstdc++] ==> lib [stdc++]
          arg [-lm] ==> lib [m]
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [-lgcc] ==> lib [gcc]
          arg [-lc] ==> lib [c]
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [-lgcc] ==> lib [gcc]
          arg [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o] ==> obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o]
          arg [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crtn.o] ==> obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crtn.o]
        collapse obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/Scrt1.o] ==> [/lib64/Scrt1.o]
        collapse obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crti.o] ==> [/lib64/crti.o]
        collapse obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o] ==> [/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o]
        collapse obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o] ==> [/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o]
        collapse obj [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64/crtn.o] ==> [/lib64/crtn.o]
        collapse library dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1] ==> [/lib64/gcc/x86_64-pc-linux-gnu/13.2.1]
        collapse library dir [/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib64] ==> [/lib64]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/usr/bin/../lib] ==> [/usr/lib]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [stdc++;m;gcc_s;gcc;c;gcc_s;gcc]
        implicit objs: [/lib64/Scrt1.o;/lib64/crti.o;/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtbeginS.o;/lib64/gcc/x86_64-pc-linux-gnu/13.2.1/crtendS.o;/lib64/crtn.o]
        implicit dirs: [/lib64/gcc/x86_64-pc-linux-gnu/13.2.1;/lib64;/usr/lib64;/usr/lib;/lib]
        implicit fwks: []
      
      
...
